### ISSUE TITLE
Import error

### ISSUE THREAD

**Issue by 2black0** [rendicahya/sinta-scraper#3]
![image](https://user-images.githubusercontent.com/9410351/176990362-80c6d430-2b66-44bd-a1f6-72a730b1af2e.png)

hi @rendicahya thanks for making this great tool
anyway I face an issue, after installation with no error I can't import the library

maybe any step I miss in installation process?
thanks

**Comment by 2black0** [comment]
after some trying,`import sinta` is the right way

but still happen some problem, the result is empty
![image](https://user-images.githubusercontent.com/9410351/176992502-7c01e899-44f3-4b51-aca8-5e5a46a281a7.png)

maybe any update?

**Comment by rendicahya** [comment]
Thank you for posting the issue and sorry for the late response. This library is written to scrape SINTA version 2 (https://sinta.kemdikbud.go.id) when the development of SINTA version 3 (https://sinta3.kemdikbud.go.id) has also been started. Notice the difference of the URL between the two.

However, it turns out that SINTA version 2 has been dropped recently. So, https://sinta.kemdikbud.go.id now points to SINTA version 3 and it is now safe to say that this library is now obsolete.

Please use sinta3-scraper (GitHub: https://github.com/rendicahya/sinta3-scraper, PyPI: https://pypi.org/project/sinta3-scraper) from now on and please understand that the development is a bit slow since I am the sole maintainer of the project.
